### PR TITLE
PR for buffer bug and file upload

### LINKED ISSUE #6: File uploads

### PR DESCRIPTION
**Pull request by bomanviktor**
This will allow the server to keep reading from the stream until all bytes are read.

To avoid out of range errors, move the `&req_str[body_start_index + 4..]` inside the if statement for chunked

Also remove the files big.png and dir.html from root

To test this:

1. Increase the body size so it is large enough for the file.

2. Add a new route to the config, give it at least POST as allowed methods (good idea to give post and get so you can try and get the files too). I prefer to use the `/files` route.

3. Go into postman. Make a new request. Change method to POST. Example URL: `http://localhost:8080/files/<filename with extension>`

4. In body, in postman. Choose `binary`, and select the file.

5. Send the request

This takes care of the file upload requirement #6 

Also take care of testing #5

### CODE REVIEW

**Review by FinnTune — CHANGES_REQUESTED** [review]
Ran into a couple issues.

1) The PR branch is running into the same problem I did with the testing. That's why I set up the test server the way I did. You can run the tests repeatedly over and over again and will get different results. Sometimes they all pass and sometimes a couple fail.


`test result: FAILED. 11 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out; finished in 0.06s`
`test result: FAILED. 10 passed; 2 failed; 2 ignored; 0 measured; 0 filtered out; finished in 0.03s`

```failures:

---- test_handle_client::cgi_request stdout ----
thread 'test_handle_client::cgi_request' panicked at tests/integration_tests.rs:40:9:
assertion `left == right` failed
  left: 500
 right: 200
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_handle_client::binary_file::valid::post stdout ----
thread 'test_handle_client::binary_file::valid::post' panicked at tests/common.rs:53:43:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(8080), path: "/files/tests.png", query: None, fragment: None }, source: hyper::Error(IncompleteMessage) }````

2) The log files from the testing are all ending up in the `log_files` directory and not `test_log_files`. Also the previous log files are no longer being overwritten during consecutive testing.

**Review by Villepat — APPROVED** [review]
The following comment is a little unclear:
"To avoid out of range errors, move the &req_str[body_start_index + 4..] inside the if statement for chunked"

**Comment by bomanviktor** [comment]
> The following comment is a little unclear: "To avoid out of range errors, move the &req_str[body_start_index + 4..] inside the if statement for chunked"

We went out of range sometimes if it was chunked.

**Review by jo-eman — APPROVED** [review]
POST of big pngs now work better

**Pull request merged**
