### PR TITLE
Features/methodtests

### PR DESCRIPTION
**Pull request by Villepat**
Unit testing for methods

### CODE REVIEW

**Review by jo-eman — APPROVED** [review]
LGTM

**Review by FinnTune — APPROVED** [review]
LGTM

**Comment by bomanviktor** [comment]
https://gist.github.com/luismts/495d982e8c5b1a0ced4a57cf3d93cf60

**Comment by bomanviktor** [comment]
And all of your commits can be squashed. The first 5 should be squashed into one commit appropriately named `Add unit tests for HTTP methods`.

Last commit could potentially be named `Rebase onto main`

**Review by bomanviktor — CHANGES_REQUESTED** [review]
Revert changes in methods.rs

Slight adjustments to unit_tests.rs (i will fix this)

**Pull request merged**
